name: Sync README

on:
  push:
    branches:
      - master
    paths:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync README
        uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: ${{ secrets.DOCKER_PASS }}
          description: https://github.com/USED255/dnsmasq
